<?php
  $adlogica_digital_data_enabled         = Mage::getStoreConfig('adlogica/adlogica_digital_data_enabled');

  $observer = 'digital_data_main/page_observer';
  $mage = Mage::getSingleton($observer);

?>

<?php if ($adlogica_digital_data_enabled == 1) :?>
<?php
  // extract variable only when digital data is enabled 
  $version         = $mage->getVersion();
  $page            = $mage->getPage();
  $user            = $mage->getUser();
  $product         = $mage->getProduct();
  $basket          = $mage->getBasket();
  $listing         = $mage->getListing();
  $transaction     = $mage->getTransaction();
  $magento_version = $mage->getMageVersion();
  $events          = $mage->getEvents();
?>
<!-- Digital Data Start -->
<script type="text/javascript">
  window.digitalData = window.digitalData || {};
  window.digitalData.version         = <?php echo json_encode($version); ?>;
  window.digitalData.magento_version = <?php echo json_encode($magento_version) ?>;
  window.digitalData.page            = <?php echo json_encode($page); ?>;
  window.digitalData.user            = <?php echo json_encode($user); ?>;
  <?php if ($product) : ?>
  window.digitalData.product = [];
  window.digitalData.product[0]         = <?php echo json_encode($product) ?>;
  <?php endif; ?>
  <?php if ($basket) : ?>
  window.digitalData.basket          = <?php echo json_encode($basket) ?>;
  <?php endif; ?>
  <?php if ($listing): ?>
  window.digitalData.listing         = <?php echo json_encode($listing) ?>;
  <?php endif; ?>
  <?php if ($transaction): ?>
  window.digitalData.transaction     = <?php echo json_encode($transaction) ?>;
  <?php endif; ?> 
  window.digitalData.events          = <?php echo json_encode($events); ?>;

</script>
<!-- Digital Data End -->
<?php endif;?>

